# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#  schedule:
#    - cron: "0 0 * * *"

name: archive

jobs:
  render:
    name: archive
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      GH_KEY: ${{ secrets.GH_KEY }}
      GH_SECRET: ${{ secrets.GH_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("gh", "aws.s3", "purrr", "curl"))'
      - name: Copy data
        run: Rscript -e 'source("R/archive.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
